name: Manual Flutter APK Build

on:
  workflow_dispatch:
    inputs:
      build_name:
        description: 'Build name (e.g. 1.0.0)'
        required: true
        default: '1.0.0'
      build_number:
        description: 'Build number (e.g. 100 or timestamp)'
        required: true
        default: '1'

jobs:
  build:
    name: Build Android AAB & APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'
          channel: stable
          architecture: x64

      - name: Install dependencies
        run: flutter pub get

      - name: Clean project
        run: flutter clean

      - name: Analyze project
        run: |
          flutter analyze > analysis.log || true
          cat analysis.log
          if grep -q "error •" analysis.log; then
            echo "❌ Flutter analysis failed"
            exit 1
          else
            echo "✅ Flutter analysis passed"
          fi

      - name: Build AAB (Android App Bundle)
        run: flutter build appbundle --release --shrink \
          --build-name="${{ github.event.inputs.build_name }}" \
          --build-number="${{ github.event.inputs.build_number }}"

      - name: Build APK (Split-per-ABI)
        run: flutter build apk --release --split-per-abi \
          --build-name="${{ github.event.inputs.build_name }}" \
          --build-number="${{ github.event.inputs.build_number }}"

      - name: Build Universal APK
        run: flutter build apk --release --no-shrink \
          --build-name="${{ github.event.inputs.build_name }}" \
          --build-number="${{ github.event.inputs.build_number }}"

      - name: Rename build files with version
        run: |
          mkdir -p release
          cp build/app/outputs/bundle/release/app-release.aab \
            release/app-${{ github.event.inputs.build_name }}-${{ github.event.inputs.build_number }}.aab
          cp build/app/outputs/flutter-apk/app-arm64-v8a-release.apk \
            release/app-arm64-${{ github.event.inputs.build_name }}-${{ github.event.inputs.build_number }}.apk
          cp build/app/outputs/flutter-apk/app-universal-release.apk \
            release/app-universal-${{ github.event.inputs.build_name }}-${{ github.event.inputs.build_number }}.apk

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: flutter-build-${{ github.event.inputs.build_name }}-${{ github.event.inputs.build_number }}
          path: release/
